extends: default

rules:
  line-length:
    max: 120
    level: warning
  document-start: disable
  indentation:
    spaces: 2
    indent-sequences: true
  trailing-spaces: enable
  empty-lines:
    max: 1
    max-end: 1
  key-duplicates: enable
  new-line-at-end-of-file: enable
  new-lines:
    type: unix
  hyphens:
    max-spaces-after: 1
  colons:
    max-spaces-before: 0
    max-spaces-after: 1
