name: Validate definition

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      working-directory: validation
      run: npm install

    - name: Run lint
      working-directory: validation
      run: npm run lint

    - name: Run tests
      working-directory: validation
      run: npm test
